project_id = "jadyybxjkluwyjfuocyc"

[functions.dia-login]
verify_jwt = false

[functions.dia-genel-rapor]
verify_jwt = false

[functions.dia-satis-rapor]
verify_jwt = false

[functions.dia-finans-rapor]
verify_jwt = false

[functions.dia-data-sync]
verify_jwt = false

[functions.dia-api-test]
verify_jwt = false
